apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ NAME }}
spec:
  schedule: "{{ SCHEDULER }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nikto
            image: sammascanner/nikto:v0.2
            env:
              - name: TARGET
                value: {{ TARGET }}
              - name: SAMMA_IO_SCANNER
                value: nikto
            {% for user in ENV %}
              - name: {{ user }}
                value: "{{ ENV[user] }}"
            {% endfor %}
          restartPolicy: Never
