apiVersion: apps/v1
kind: Deployment
metadata:
  name: samma-service
  namespace: samma-io
spec:
  selector:
    matchLabels:
      app: samma-service
  template:
    metadata:
      labels:
        app: samma-service
    spec:
      serviceAccountName: samma-operator
      containers:
        - image: sammascanner/operator
          name: samma-service
          imagePullPolicy: Never
          #command: ['python','-u','/code/service_watch.py']        