version: '3'
services:
  operator:
    build: operator/.
    image: sammascanner/operator:beta
    volumes:
      - ./:/code
    ports:
      - 8888:80
  api:
    build: api/.
    image: sammascanner/api:beta
    volumes:
      - ./:/code
    ports:
      - 8888:80