apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: operator
build:
  artifacts:
  - image: sammascanner/operator
    context: operator
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifest/install.yaml
    - manifest/test/nmap.yaml
    - operator/k8s/deploy.yaml
    - operator/test/samma.yaml
    - operator/test/service.yaml
