---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ NAME }}
spec:
  template:
    spec:
      containers:
      - name: nikto
        image: sammascanner/nikto:v0.2
        env:
          - name: TARGET
            value: {{ TARGET }}
          - name: SAMMA_IO_SCANNER
            value: nikto
        {% for user in ENV %}
          - name: {{ user }}
            value: "{{ ENV[user] }}"
        {% endfor %}
      restartPolicy: Never
