---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ NAME }}
spec:
  template:
    spec:
      containers:
      - name: nikto
        image: sammascanner/nikto:v0.2
        command: ["python3","/code/scan.py","&","echo","'died_man_die'",">","/out/die"]
        env:
          - name: TARGET
            value: {{ TARGET }}
        {% for user in ENV %}
          - name: {{ user }}
            value: "{{ ENV[user]}}"
        {% endfor %}
          - name: PARSER
            value: nikto
        volumeMounts:
          - mountPath: /out
            name: out-volume
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        env:
          - name: ELASTICSEARC
            value: http://elasticsearch:9200
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - '-c'
              - /live.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: filebeat
          mountPath: "/usr/share/filebeat/filebeat.yml"
          subPath: "filebeat.yml"
        - name: liveness
          mountPath: "/live.sh"
          subPath: "live.sh"
        - mountPath: /out
          name: out-volume
      volumes:
      - name: filebeat
        configMap:
          name: filebeat
      - name: liveness
        configMap:
          name: live
          defaultMode: 0777
      - name: out-volume
        emptyDir: {}
      restartPolicy: Never
