---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ NAME }}-tls
spec:
  template:
    spec:
      containers:
      - name: nmap-tls
        image: sammascanner/nmap:v0.2
        command: ["python3","/code/nmap_tlscipher.py"]
        env:
          - name: TARGET
            value: {{ TARGET }}
          - name: SAMMA_IO_SCANNER
            value: nmap
        {% for user in ENV %}
          - name: {{ user }}
            value: "{{ ENV[user] }}"
        {% endfor %}
      restartPolicy: Never
