apiVersion: v1
kind: Namespace
metadata:
  name: samma-io
---
apiVersion: apiextensions.k8s.io/v1 
kind: CustomResourceDefinition 
metadata: 
  name: scanner.samma.io 
spec: 
  scope: Namespaced 
  group: samma.io
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                target:
                  type: string
                ip:
                  type: string
                scanners:
                  type: array
                  items:
                    type: string
                samma_io_id:
                  type: string
                samma_io_tags:
                  type: array 
                  items:
                    type: string
                samma_io_json:
                  type: string
                write_to_file:
                  type: string
                elasticsearch:
                  type: string

  names: 
    kind: Scanner
    plural: scanner
    singular: scanner 
    shortNames: 
      - sc
---
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: samma-operator
  namespace: samma-io
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: samma-operator 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: cluster-admin 
subjects: 
  - kind: ServiceAccount 
    name: samma-operator 
    namespace: samma-io 
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: samma-operator
#spec:
#  selector:
#    matchLabels:
#      app: samma-operator
#  template:
#    metadata:
#      labels:
#        app: samma-operator
#    spec:
#      serviceAccountName: samma-operator
#      containers:
#        - image: sammascanner/operator
#          name: samma-operator
#          imagePullPolicy: Always