apiVersion: v1
kind: Namespace
metadata:
  name: samma-io
---
apiVersion: apiextensions.k8s.io/v1 
kind: CustomResourceDefinition 
metadata: 
  name: scanner.samma.io 
spec: 
  scope: Namespaced 
  group: samma.io
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                target:
                  type: string
                ip:
                  type: string
                scheduler:
                  type: string
                scanners:
                  type: array
                  items:
                    type: string
                samma_io_json:
                  type: string
                samma_io_id:
                  type: string
                samma_io_tags:
                  type: array
                  items:
                    type: string
                write_to_file:
                  type: string
                elasticsearch:
                  type: string

  names: 
    kind: Scanner
    plural: scanner
    singular: scanner 
    shortNames: 
      - sc
---
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: samma-operator
  namespace: samma-io
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: samma-operator 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: cluster-admin 
subjects: 
  - kind: ServiceAccount 
    name: samma-operator 
    namespace: samma-io 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samma-operator
  namespace: samma-io
spec:
  selector:
    matchLabels:
      app: samma-operator
  template:
    metadata:
      labels:
        app: samma-operator
    spec:
      serviceAccountName: samma-operator
      containers:
        - image: sammascanner/operator:beta
          env:
            - name: nats
              value: nats
            - name: samma_io_id
              value: "12345"
            - name: samma_io_tags
              value: "['scanner','prod']"
            - name: samme_io_json
              value: '{"attacke":"true"}'
            - name: write_to_file
              value: "true"
            - name: elasticsearch
              value: elasticsearch
            - name: scanners
              value: "['nmap']"
          name: samma-operator
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samma-api
  namespace: samma-io
spec:
  selector:
    matchLabels:
      app: samma-api
  template:
    metadata:
      labels:
        app: samma-api
    spec:
      serviceAccountName: samma-operator
      containers:
        - image: sammascanner/api:beta
          name: samma-api
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: samma-io
spec:
  ports:
  - port: 80
    name: api
    targetPort: 80
  selector:
    app: samma-api
  type: NodePort
