apiVersion: batch/v1
kind: Job
metadata:
  name: {{ NAME }}
spec:
  template:
    spec:
      containers:
      - name: traceroute-scanner
        image: ghcr.io/samma-io/detect-traceroute-scanner:latest
        env:
          - name: TARGET
            value: {{ TARGET }}
          - name: SAMMA_IO_SCANNER
            value: traceroute-scanner
        {% for user in ENV %}
          - name: {{ user }}
            value: "{{ ENV[user] }}"
        {% endfor %}
      restartPolicy: Never
