apiVersion: batch/v1
kind: Job
metadata:
  name: {{ NAME }}-tsunami
spec:
  template:
    spec:
      containers:
      - name: tsunami
        image: sammascanner/tsunami:v0.1
        {% if SCANNERFirst is number %}
        args: ["--ip-v4-target={{ TARGET }}","--scan-results-local-output-format=JSON","--scan-results-local-output-filename=/out/tsunami-output.json"]
        {% else %}
        args: ["--hostname-target={{ TARGET }}","--scan-results-local-output-format=JSON","--scan-results-local-output-filename=/out/tsunami-output.json"]
        {% endif %}
        env:
          - name: TARGET
            value: {{ TARGET }}
          - name: SAMMA_IO_SCANNER
            value: tsunami
        {% for user in ENV %}
          - name: {{ user }}
            value: "{{ ENV[user] }}"
        {% endfor %}
      restartPolicy: Never
