apiVersion: apps/v1
kind: Deployment
metadata:
  name: samma-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: samma-api
  template:
    metadata:
      labels:
        app: samma-api
    spec:
      serviceAccountName: samma-operator
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: samma-api
          image: {{ .Values.api.image }}:{{ .Values.api.tag }}
          imagePullPolicy: {{ .Values.api.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SAMMA_IO_ID
              value: {{ .Values.config.sammaIoId | quote }}
            - name: SAMMA_IO_TAGS
              value: {{ .Values.config.sammaIoTags | quote }}
            - name: SAMMA_IO_JSON
              value: {{ .Values.config.sammaIoJson | quote }}
            - name: WRITE_TO_FILE
              value: {{ .Values.config.writeToFile | quote }}
            - name: SAMMA_IO_API_URL
              value: {{ .Values.config.apiUrl | quote }}
            - name: SAMMA_IO_API_TOKEN
              value: {{ .Values.config.apiToken | quote }}
            - name: SAMMA_IO_PROFILE_ID
              value: {{ .Values.config.profileId | quote }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: samma-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
