apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.timescaledb.storageClass }}
  storageClassName: {{ .Values.timescaledb.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.timescaledb.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: timescaledb
          image: {{ .Values.timescaledb.image }}:{{ .Values.timescaledb.tag }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.timescaledb.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.timescaledb.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.timescaledb.password | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
          resources:
            {{- toYaml .Values.timescaledb.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timescaledb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: timescaledb
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
