apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ NAME }}
spec:
  schedule: "{{ SCHEDULER }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: port-scanner
            image: ghcr.io/samma-io/detect-port-scanner:latest
            env:
              - name: TARGET
                value: {{ TARGET }}
              - name: SAMMA_IO_SCANNER
                value: port-scanner
            {% for user in ENV %}
              - name: {{ user }}
                value: "{{ ENV[user] }}"
            {% endfor %}
          restartPolicy: Never
